const c=document.getElementById('gameCanvas'),x=c.getContext('2d'),W=c.width,H=c.height;
const ui={score:document.getElementById('score'),time:document.getElementById('time'),streak:document.getElementById('streak'),start:document.getElementById('start'),pause:document.getElementById('pause'),end:document.getElementById('end'),endTitle:document.getElementById('endTitle'),endText:document.getElementById('endText')};
const startBtn=document.getElementById('startBtn'),againBtn=document.getElementById('againBtn'),resumeBtn=document.getElementById('resumeBtn'),pauseBtn=document.getElementById('pauseBtn');
let run=false,paused=false,last=0,t=0,score=0,streak=0,collected=0,sparks=[],enemies=[],parts=[],keys=new Set();
const p={x:120,y:H/2,r:18,s:250,shield:0},portal={x:W-90,y:H/2,r:36},spawn={s:0,e:0};
function R(a,b){return Math.random()*(b-a)+a}
function D(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function burst(a,b,col,n=12){for(let i=0;i<n;i++)parts.push({x:a,y:b,vx:R(-140,140),vy:R(-140,140),life:R(.2,.6),col})}
function spark(){sparks.push({x:R(210,W-170),y:R(50,H-50),r:9,ph:R(0,6.3)})}
function enemy(){enemies.push({x:R(300,W-110),y:R(40,H-40),r:16,vx:R(-90,90),vy:R(-90,90),turn:R(.5,1.5)})}
function clearKeys(){keys.clear()}
function reset(){run=true;paused=false;last=performance.now();t=0;score=0;streak=0;collected=0;sparks=[];enemies=[];parts=[];spawn.s=0;spawn.e=0;p.x=120;p.y=H/2;p.shield=0;clearKeys();ui.score.textContent=0;ui.streak.textContent=0;ui.time.textContent=60;ui.start.classList.add('hidden');ui.pause.classList.add('hidden');ui.end.classList.add('hidden');for(let i=0;i<7;i++)spark();for(let i=0;i<2;i++)enemy();requestAnimationFrame(loop)}
function endGame(title){run=false;clearKeys();ui.endTitle.textContent=title;ui.endText.textContent=`Final score: ${score} • Streak: ${streak}`;ui.end.classList.remove('hidden')}
function update(dt){t+=dt;let dx=(keys.has('ArrowRight')||keys.has('d'))-(keys.has('ArrowLeft')||keys.has('a')),dy=(keys.has('ArrowDown')||keys.has('s'))-(keys.has('ArrowUp')||keys.has('w'));if(dx||dy){let l=Math.hypot(dx,dy);p.x+=dx/l*p.s*dt;p.y+=dy/l*p.s*dt}p.x=Math.max(30,Math.min(W-30,p.x));p.y=Math.max(30,Math.min(H-30,p.y));spawn.s+=dt;spawn.e+=dt;if(spawn.s>2.2&&sparks.length<9){spawn.s=0;spark()}if(spawn.e>5&&enemies.length<6){spawn.e=0;enemy()}
for(let i=sparks.length-1;i>=0;i--){let q=sparks[i];q.ph+=dt*3;if(D(p,q)<p.r+q.r+5){burst(q.x,q.y,'#ffd52b');sparks.splice(i,1);collected++;streak++;score+=10+Math.min(streak,10)*2;ui.score.textContent=score;ui.streak.textContent=streak;p.shield=Math.min(2,p.shield+.25)}}
for(let i=enemies.length-1;i>=0;i--){let e=enemies[i];e.turn-=dt;if(e.turn<=0){e.turn=R(.5,1.5);e.vx=R(-100,100);e.vy=R(-100,100)}e.x+=e.vx*dt;e.y+=e.vy*dt;if(e.x<25||e.x>W-25)e.vx*=-1;if(e.y<25||e.y>H-25)e.vy*=-1;if(D(p,e)<p.r+e.r){if(p.shield>=1){p.shield-=1;burst(e.x,e.y,'#37dfff',18);e.x=R(320,W-80);e.y=R(50,H-50)}else{streak=0;score=Math.max(0,score-15);ui.score.textContent=score;ui.streak.textContent=0;burst(p.x,p.y,'#ff4961',15);p.x=120;p.y=H/2}}}
for(let i=parts.length-1;i>=0;i--){let q=parts[i];q.x+=q.vx*dt;q.y+=q.vy*dt;q.life-=dt;if(q.life<=0)parts.splice(i,1)}portal.y=H/2+Math.sin(t*.8)*120;if(t>=60){endGame('Time Up!');return}if(collected>0&&D(p,portal)<p.r+portal.r){score+=50;ui.score.textContent=score;endGame('Portal Reached!');return}ui.time.textContent=Math.max(0,Math.ceil(60-t))}
function draw(){let g=x.createLinearGradient(0,0,0,H);g.addColorStop(0,'#d8f7ff');g.addColorStop(1,'#8ed6ef');x.fillStyle=g;x.fillRect(0,0,W,H);for(let y=45;y<H;y+=90){x.strokeStyle='rgba(255,255,255,.28)';x.beginPath();x.moveTo(0,y);x.lineTo(W,y+50);x.stroke()}for(let q of sparks){let r=q.r+Math.sin(q.ph)*2;x.beginPath();x.arc(q.x,q.y,r+7,0,7);x.fillStyle='rgba(255,213,43,.2)';x.fill();x.beginPath();x.arc(q.x,q.y,r,0,7);x.fillStyle='#ffd52b';x.fill()}for(let e of enemies){x.save();x.translate(e.x,e.y);x.rotate(Math.atan2(e.vy,e.vx));x.fillStyle='#ff4961';x.beginPath();x.moveTo(19,0);x.lineTo(0,14);x.lineTo(-13,0);x.lineTo(0,-14);x.closePath();x.fill();x.restore()}x.beginPath();x.arc(portal.x,portal.y,portal.r+8,0,7);x.fillStyle='rgba(55,223,255,.15)';x.fill();x.beginPath();x.arc(portal.x,portal.y,portal.r,0,7);x.fillStyle='#163b72';x.fill();x.strokeStyle='#37dfff';x.lineWidth=7;x.stroke();x.beginPath();x.arc(p.x,p.y,p.r+8,0,7);x.fillStyle='rgba(55,223,255,.25)';x.fill();x.beginPath();x.arc(p.x,p.y,p.r,0,7);x.fillStyle='#effcff';x.fill();x.strokeStyle='#169eef';x.lineWidth=5;x.stroke();if(p.shield>0){x.beginPath();x.arc(p.x,p.y,p.r+14,0,7);x.strokeStyle='rgba(55,223,255,.85)';x.lineWidth=4;x.stroke()}for(let q of parts){x.globalAlpha=Math.max(0,q.life*2);x.fillStyle=q.col;x.fillRect(q.x,q.y,4,4)}x.globalAlpha=1;x.fillStyle='rgba(5,22,42,.65)';x.fillRect(18,18,300,40);x.fillStyle='#fff';x.font='700 16px system-ui';x.fillText(collected?'Collect sparks → Reach portal':'Collect a spark to unlock portal',32,44)}
function loop(now){if(!run)return;let dt=Math.min(.032,(now-last)/1000);last=now;if(!paused){update(dt);draw()}if(run)requestAnimationFrame(loop)}
function pauseToggle(){if(!run)return;paused=!paused;clearKeys();ui.pause.classList.toggle('hidden',!paused)}
function normalizeKey(key){return key.length===1?key.toLowerCase():key}
addEventListener('keydown',e=>{let key=normalizeKey(e.key);if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(key))e.preventDefault();if(key===' ')pauseToggle();else keys.add(key)});
addEventListener('keyup',e=>keys.delete(normalizeKey(e.key)));
addEventListener('blur',clearKeys);
document.addEventListener('visibilitychange',()=>{clearKeys();if(document.hidden&&run&&!paused)pauseToggle()});
startBtn.onclick=reset;againBtn.onclick=reset;resumeBtn.onclick=pauseToggle;pauseBtn.onclick=pauseToggle;
document.querySelectorAll('.mobile button').forEach(button=>{let key=button.dataset.k;let release=event=>{keys.delete(key);if(event.pointerId!==undefined&&button.hasPointerCapture?.(event.pointerId))button.releasePointerCapture(event.pointerId)};button.addEventListener('pointerdown',event=>{event.preventDefault();button.setPointerCapture?.(event.pointerId);keys.add(key)});['pointerup','pointercancel','pointerleave','lostpointercapture'].forEach(type=>button.addEventListener(type,release))});
draw();
